### ISSUE TITLE
Page footer can hide options

### ISSUE THREAD

**Issue by JaSpa** [mipmip/home-manager-option-search#46]
Firstly, thank you for this page. It vastly improves the user experience when browsing home-manager options!

When searching for a term with a many results, e.g. [`neomutt` in release 24.05](https://home-manager-options.extranix.com/?query=neomutt&release=release-24.05), the page footer covers options at the end of table. Scrolling further to make them visible is not possible.

I observe this behaviour on Firefox 130, Safari 17.6, and Arc 1.61 on macOS.

**Comment by JaSpa** [comment]
These changes would fix the issue while preserving the current behaviour (footer always visible at the bottom of the screen):

```css
.navbar-fixed-bottom {
  position: sticky; /* currently it is "fixed" */
}
.xcontainer {
  flex-grow: 1; /* currently unset */
}
```

I haven't looked at the CSS enough to know if this might break other areas. But if this looks reasonable to you I can prepare a patch.
